name: Build All Devices with PlatformIO

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: false

    - name: Setup Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add original repository as upstream
      run: git remote add upstream https://github.com/pr3y/Bruce

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Stash changes in rf.cpp
      run: |
        git stash push -m "Stash changes in rf.cpp" src/modules/rf/rf.cpp

    - name: Rebase onto upstream/main
      run: git merge --allow-unrelated-histories --no-edit upstream/main

    - name: Pop the stashed changes in rf.cpp
      run: |
        git stash pop

    - name: Push changes to your repository
      run: git push origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: update-fork

    steps:
    - name: Checkout updated repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build with PlatformIO for All Devices
      run: |
        platformio run -t clean
        platformio run 

    - name: Move binaries to 'teste' folder
      run: |
        mkdir -p teste
        cp .pio/build/*/firmware.bin teste/ # Atualize o caminho se necessário