name: Build Bruce Firmware

on:
  schedule:
    - cron: '0 0 * * *'  # Roda 1x por dia
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Evita sobrescrever o fork

      - name: Criar Backup do rf.cpp
        run: cp src/modules/rf/rf.cpp rf_backup.cpp

      - name: Adicionar repositório original como upstream
  run: |
    git remote add upstream https://github.com/brucecoredev/Bruce.git
    git fetch upstream

     - name: Fazer merge das atualizações do repositório original
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/brucecoredev/Bruce.git main

      - name: Restaurar rf.cpp do Fork
        run: mv rf_backup.cpp src/modules/rf/rf.cpp

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Compilar Firmware
        run: platformio run

      - name: Mover Bins para Pasta "teste"
        run: |
          mkdir -p teste
          find .pio/build/ -name "*.bin" -exec mv {} teste/ \;

      - name: Commit e Push dos arquivos compilados
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git add teste/
    git commit -m "Adicionando firmware compilado automaticamente" || echo "Nenhuma mudança para commitar"
    git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main